### ISSUE TITLE
micropip

### ISSUE THREAD

**Issue by gabriel-v** [pygame-web/pkg-porting-wasm#8]
I see micropip is packaged in the archive, but importing it doesn't work.

In browser REPL at `/#debug`:

```
>>> import micropip
181: FIXME dependency table for manually built modules
pkg : http://localhost:8000/archives/repo/pkg/micropip-0.1.0-py3-none-any.whl
 |XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| 100.0% 
resume=<function <module> at 0xe54208> is not awaitable
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/micropip/_micropip.py", line 17, in <module>
    from packaging.markers import default_environment
ModuleNotFoundError: No module named 'packaging'

>>> import micropip
181: FIXME dependency table for manually built modules
pkg : http://localhost:8000/archives/repo/pkg/packaging-21.3-py3-none-any.whl
 |XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| 100.0% 
resume=<function <module> at 0xe54208> is not awaitable
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/packaging/markers.py", line 11, in <module>
    from pyparsing import (  # noqa: N817
ModuleNotFoundError: No module named 'pyparsing'

>>> import micropip
181: FIXME dependency table for manually built modules
pkg : http://localhost:8000/archives/repo/pkg/pyparsing-3.0.9-py3-none-any.whl
 |XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| 100.0% 
resume=<function <module> at 0xe54208> is not awaitable
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/micropip/_micropip.py", line 22, in <module>
    from pyodide._package_loader import get_dynlibs, wheel_dist_info_dir
ModuleNotFoundError: No module named 'pyodide'

>>> import micropip
181: FIXME dependency table for manually built modules
PKG NOT FOUND : want='pyodide', resume=<function <module> at 0x8cf9e0>, ex=ModuleNotFoundError("No module named 'pyodide'")
>>> 
>>> import micropip
181: FIXME dependency table for manually built modules
PKG NOT FOUND : want='pyodide', resume=<function <module> at 0x8cf9e0>, ex=ModuleNotFoundError("No module named 'pyodide'")
>>> 

```

But if you vendor the `micropip` [python code](https://github.com/pyodide/micropip/tree/9416cb029511af9543a4682c8e9823447c18f3de/micropip) next to `main.py` like this: https://github.com/gabriel-v/python-wasm-pygame-experiments/tree/c18cd2e7d846d371e2a9ae5d92e1812e507d7665/src/micropip/micropip

And edit  `micropip/_compat_not_in_pyodide.py` method `async def fetch_bytes()` to [use platform.fopen](https://github.com/gabriel-v/python-wasm-pygame-experiments/blob/c18cd2e7d846d371e2a9ae5d92e1812e507d7665/src/micropip/micropip/_compat_not_in_pyodide.py#L22-L31) instead of [urllib.request.urlopen](https://github.com/pyodide/micropip/blob/9416cb029511af9543a4682c8e9823447c18f3de/micropip/_compat_not_in_pyodide.py#L20)

then you get a working browser micropip:

```
>>> import micropip
>>> await micropip.install('jmespath')
>>> import jmespath
```

Is this a problem in the wheel (dependency towards pyodide?) or the pygbag import hooks (detected imports for pyodide in the other module we don't run, `_compat_in_pyodide.py`), or something else?

**Comment by pmp-p** [comment]
Tbh i only used the micropip and friends to test dependency solver when reading from pyodide's repodata json and i forgot to remove them. i'll clean them up
pygbag runtime uses pypa/installer and emscripten api to load wheels

**Comment by tigercoding56** [comment]
> Tbh i only used the micropip and friends to test dependency solver when reading from pyodide's repodata json and i forgot to remove them. i'll clean them up pygbag runtime uses pypa/installer and emscripten dlfcn implementation to load wheels that is a behaviour much more close to stock cpython than pyodide's approach (which was started based on asm.js )

https://github.com/pypa/installer ?

**Comment by pmp-p** [comment]
yes the pep 0723 prototype uses that
and micropip will be removed from repo
